ruby '2.2.1'

source 'https://rubygems.org'

gem 'sinatra'
gem 'activerecord'
gem 'json'
gem 'typhoeus'
gem 'rspec'
gem 'sqlite3'
gem 'rack-test'
gem 'sinatra-jsonp'
gem 'sinatra-cross_origin'
gem 'sinatra-activerecord'
