require 'rubygems' 
require 'active_record' 
require 'yaml'
require 'rake'
require 'rspec/core/rake_task'



desc "Load the environment" 
task :environment do
  env = ENV["SINATRA_ENV"] || "development"
  databases = YAML.load_file("config/database.yml") 
  ActiveRecord::Base.establish_connection(databases[env])
end

task(:test => ["db:migrate", :spec]) do

end

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = Dir.glob('spec/**/*_spec.rb')
end

namespace :db do
  desc "Migrate the database" 
  task(:migrate => :environment) do
    ActiveRecord::Base.logger = Logger.new(STDOUT) 
    ActiveRecord::Migration.verbose = true 
    ActiveRecord::Migrator.migrate("db/migrate")
  end 
end


namespace :app do
  desc "Run the app in dev mode"
  task(:run => [:environment, "db:migrate"]) do
    `ruby service.rb`
  end
end
